# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i -g @angular/cli@9.0.6
        name: Install angular CLI
      - run: npm install
        name: Install dependencies
      - run: ng build --prod
        name: Production Build
      - name: create fallback 404 file
        run: cp dist/identity-adm/index.html dist/identity-adm/404.html
      - name: create cname file
        run: echo "admin.prasenjit.net" > dist/identity-adm/CNAME
      - name: GitHub Pages Deployment
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          # GitHub repository where assets will be deployed (default current)
          # repo: # optional
          # Git branch where assets will be deployed
          # target_branch: # optional, default is gh-pages
          # Create incremental commit instead of doing push force
          # keep_history: # optional, default is false
          # Allow an empty commit to be created
          # allow_empty_commit: # optional, default is true
          # Build directory to deploy
          build_dir: dist/identity-adm
          # Commit author's name
          # committer_name: # optional
          # Commit author's email
          # committer_email: # optional
          # Commit message
          # commit_message: # optional
          # Write the given domain name to the CNAME file
          # fqdn: # optional
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
